# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  ENV['LC_ALL']="en_US.UTF-8"

  # faster for local purposes
  config.ssh.insert_key = false

  #terraform
  config.vm.define "terraform" do |terraform|
    terraform.vm.box = "centos/7"
    terraform.vm.hostname = "terraform"
    terraform.vm.network :private_network, ip: "192.168.7.71"

    config.vm.provider :virtualbox do |vb|
      vb.memory = 2560
      vb.cpus = 2
    end

    terraform.vm.provision :ansible do |ansible|
       ansible.galaxy_role_file = "requirements.yml"
       ansible.playbook = "playbook.yml"

       # ansible.become = true
     end
  end

end
