# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "docker-compose"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "docker-compose"
    vb.memory = "1536"
  end

  config.vm.provision :shell, path: "./docker-compose-provision.sh"
  
end
