# -*- mode: ruby -*-
# vi: set ft=ruby :

$TMP_JENKINS="/tmp/jenkins"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  ENV['LC_ALL']="en_US.UTF-8"
  config.vm.hostname = "jenkins-master"

  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.provider "virtualbox" do |vb|
    vb.name = "jenkins-master"
    vb.gui = false
    vb.memory = "2560" # jenkins java_ops Xmx2048m
    vb.cpus = 2
  end

  config.vm.provision "file", source: "./Dockerfile", destination: "#{$TMP_JENKINS}/Dockerfile"
  config.vm.provision "file", source: "./plugins.txt", destination: "#{$TMP_JENKINS}/plugins.txt"
  config.vm.provision :shell, path: "./../docker-compose/docker-compose-provision.sh"
  config.vm.provision :shell, path: "./jenkins-provision.sh"
  # SHELL
end
