# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  #workaround to avoid https://github.com/dotless-de/vagrant-vbguest/issues/351
  config.vbguest.auto_update = false 
  ENV['LC_ALL']="en_US.UTF-8"

  # faster for local purposes
  config.ssh.insert_key = false

  #minikube
  config.vm.define "minikube" do |minikube|
    minikube.vm.hostname = "minikube"
    minikube.vm.network :private_network, ip: "192.168.7.77"

    config.vm.provider :virtualbox do |vb|
      vb.memory = 6144
      vb.cpus = 2
      vb.name = "minikube"
    end

    # config.vm.provision :shell, path: "./../docker-compose/docker-compose-provision.sh"
    
    minikube.vm.provision :ansible do |ansible|
       ansible.galaxy_role_file = "requirements.yml"
       ansible.playbook = "playbook.yml"
     end

  end

end
