# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "debian/buster64"
  ENV['LC_ALL']="en_US.UTF-8"

  # faster for local purposes
  config.ssh.insert_key = false

  #terraform
  config.vm.define "ansible-bastion" do |ansiblebastion|
    ansiblebastion.vm.hostname = "ansible-bastion"
    ansiblebastion.vm.network :private_network, ip: "192.168.7.77"

    config.vm.provider :virtualbox do |vb|
      vb.memory = 2560
      vb.cpus = 2
    end

    ansiblebastion.vm.provision :ansible do |ansible|
       ansible.galaxy_role_file = "requirements.yml"
       ansible.playbook = "playbook.yml"
     end
  end

end
